apiVersion: v1
kind: Service
metadata:
  name: {{- .Values.serviceName.name | indent 2 }}
  creationTimestamp: null
  labels:
    app: {{- .Values.tagging | indent 4 }}
  
spec:
  ports:
  - name: {{- .Values.imageName.name | indent 2 }}
    nodePort: {{- .Values.port.nodePort | indent 2 }}
    port: {{- .Values.port.clusterPort | indent 2 }}
    protocol: TCP
    targetPort: {{- .Values.port.targetPort | indent 2 }}
  selector:
    app: {{- .Values.tagging | indent 4 }}
  type: {{- .Values.serviceName.service | indent 2 }}
status:
  loadBalancer: {}
  
